#!/bin/bash
# sudo pacman -S wmctrl

OS=$(cat /etc/lsb-release | awk -F '=' '/DISTRIB_ID/ {print $2}')
KERNEL=$(uname -r)
ARCH=$(uname -m)
HOSTNAME=$(hostname)
VERSION=$(cat /etc/lsb-release | awk -F '=' '/DISTRIB_RELEASE/ {print $2}')
UPTIME=$(awk '{printf("%d:%02d:%02d:%02d",($1/60/60/24),($1/60/60%24),($1/60%60),($1%60))}' /proc/uptime)
MODEL=$(cat /sys/devices/virtual/dmi/id/product_{name,version} | awk '!(NR%2){print$1,p}{p=$0}')
DE=$(wmctrl -m | awk 'NR==1 {print $2}')
CPU=$(awk < /proc/cpuinfo '/model name/{gsub(/[(TMR)]/,"");print $4,$5,$6}' | head -1)
#GPU=$(nvidia-smi --query-gpu=gpu_name --format=csv|sed -n 2p)
SHELL=$(echo "$SHELL" | awk -F/ '{for ( i=1; i <= NF; i++) sub(".", substr(toupper($i),1,1) , $i); print $NF}')
RESOLUTION=$(xdpyinfo | awk '/dimensions:/ {printf $2}')
BIRTH=$(ls -alct /|sed '$!d'|awk '{print $7, $6, $8}')

# gtk
if [ -f ~/.gtkrc-2.0 ]; then
    GtkTheme=$(awk < ~/.gtkrc-2.0 -F'"' '/gtk-theme-name/{print $2}')
    GtkIcon=$(awk < ~/.gtkrc-2.0 -F'"' '/gtk-icon-theme-name/{print $2}' )
elif [ -f ~/.config/gtk-3.0/settings.ini  ]; then
    GtkTheme=$(awk < ~/.config/gtk-3.0/settings.ini -F'=' '/gtk-theme-name/{print $2}')
    GtkIcon=$(awk < ~/.config/gtk-3.0/settings.ini -F'=' '/gtk-icon-theme-name/{print $2}' )
fi

# pkg
PKG=$(checkupdates | wc -l)
PKGINST=$(pacman -Q | wc -l)

 echo  ""
 echo -e "\e[33m   [  sysinfo  ]"
 echo -e "\e[94m     \e[39m$USER@$HOSTNAME"
 echo -e "\e[94m    \e[39m$MODEL"
 echo -e "\e[94m     \e[39m$CPU"
 echo -e "\e[94m     \e[39m$KERNEL ($OS)"
 echo -e "\e[94m     \e[39m$UPTIME"
 echo -e "\e[94m     \e[39m$SHELL"
 echo -e "\e[94m     \e[39m$RESOLUTION"
 #echo -e "\e[94m     \e[39m$GPU"
 echo -e "\e[33m   [  wm / de  ]"
 echo -e "\e[94m     \e[39m$DE"
 echo -e "\e[94m     \e[39m$GtkTheme"
 echo -e "\e[94m     \e[39m$GtkIcon"
 #echo -e "\e[94m     \e[39m$BIRTH"
 echo -e "\e[33m   [  pkg: inst / up  ]"
 echo -e "\e[94m     \e[39m$PKGINST / $PKG"
 echo  ""
